fix Error when more than one Map in same Page
L1am0/hugo-leaflet pull request #10
Opened 2024-12-08 14:56 UTC by wernerjoss

2026-06-01 09:17 UTC, simonfrey commented
Let's please remove the "css re-formatting" and the leafleat upgrade from this PR, as it would be a huge hassle for me to review the javascript script for security and is not the core of what this PR tackles. 

Recommended installation method is via remotely linked leaflet script anyways.

2026-06-01 09:17 UTC, simonfrey requested changes

2026-06-01 09:17 UTC, simonfrey commented on layouts/shortcodes/leaflet-simple.html
> +		// TODO: fix Error when loading 2 maps with exact same coordinates in one page !! 10.9.24
What is this TODO about? Can we fix it as well? 

I think the overall better fix for the "let" variable re-declaration would be to encapsule the entire init functionality into a `func()`, right? As then the let would be scoped in that function and also same coordinate re-declaration should not be an issue.

2026-06-01 09:17 UTC, simonfrey commented on layouts/shortcodes/leaflet-simple.html
> +			L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {	// avoid mixed content error for osm png's in FF 31.0.5.26
Please remove the above commented code. Your setup with "https" is better, no need to keep old code line around.

2026-06-01 18:22 UTC, wernerjoss commented on layouts/shortcodes/leaflet-simple.html
> +		// TODO: fix Error when loading 2 maps with exact same coordinates in one page !! 10.9.24
The TODO is not a redeclaration issue, but
'Map container is already initialized' in case a map with same coordinates is added.
I guess this is a very unusual use case, so I did not further investigate this.
the 'let..' fix is now done by init function, see
[this pull request](https://github.com/simonfrey/hugo-leaflet/pull/10/commits/7defb9c9d94f7d20260eaa332372bf15cf3f5ceb)

2026-06-01 18:22 UTC, wernerjoss commented on layouts/shortcodes/leaflet-simple.html
> +			L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {	// avoid mixed content error for osm png's in FF 31.0.5.26
see my [last pull request](https://github.com/simonfrey/hugo-leaflet/pull/10/commits/c5fa7493daaedb118cbc40909062fc0c8d00ff40)

2026-06-01 18:24 UTC, wernerjoss commented
> Let's please remove the "css re-formatting" and the leafleat upgrade from this PR, as it would be a huge hassle for me to review the javascript script for security and is not the core of what this PR tackles.

I'm not sure how to remove the leaflet upgrade PR, which in fact is not related to the Original PR.
so I propose to just ignore this.

2026-06-02 07:10 UTC, simonfrey commented
> I'm not sure how to remove the leaflet upgrade PR, which in fact is not related to the Original PR.

@wernerjoss You should be able to do this with "git interactive rebase" (https://www.geeksforgeeks.org/git/what-is-git-interactive-rebasing/) by "dropping" the according commits.

2026-06-08 12:50 UTC, wernerjoss commented
tried to delete the leaflet upgrade commits using several methods, none of them worked.
closing the whole PR now.

2026-06-08 12:50 UTC, closed without merging